In [6]:
import numpy as np

class HopfieldNetwork:
    def __init__(self, vector_size):
        self.vector_size = vector_size
        self.weights = np.zeros((vector_size, vector_size))

    def train(self, training_data):
        num_vectors = len(training_data)
        for vector in training_data:
            print('v', vector)
            print('op', np.outer(vector, vector))
            self.weights += np.outer(vector, vector) / num_vectors
        np.fill_diagonal(self.weights, 0)

    def predict(self, input_vector, num_iterations=5):
        output_vector = np.copy(input_vector)
        for _ in range(num_iterations):
            output_vector = np.sign(np.dot(self.weights, output_vector))
        return output_vector

# Define the training data
training_data = np.array([[1, 1, -1, -1],
                          [1, -1, 1, -1],
                          [-1, 1, -1, 1],
                          [-1, -1, 1, 1]])

# Create an instance of the HopfieldNetwork class
hopfield_net = HopfieldNetwork(vector_size=4)

# Train the Hopfield network with the training data
hopfield_net.train(training_data)

# Test the Hopfield network by retrieving the stored vectors
test_data = np.array([[1, 1, -1, -1],
                      [1, -1, -1, -1],
                      [1, -1, 1, 1]])

for input_vector in test_data:
    output_vector = hopfield_net.predict(input_vector)
    print("Input Vector:", input_vector)
    print("Output Vector:", output_vector)
    print("-------------")


v [ 1  1 -1 -1]
op [[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
v [ 1 -1  1 -1]
op [[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]
v [-1  1 -1  1]
op [[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]
v [-1 -1  1  1]
op [[ 1  1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
Input Vector: [ 1  1 -1 -1]
Output Vector: [ 1.  1. -1. -1.]
-------------
Input Vector: [ 1 -1 -1 -1]
Output Vector: [ 1.  1.  1. -1.]
-------------
Input Vector: [ 1 -1  1  1]
Output Vector: [-1. -1.  1. -1.]
-------------
